### ISSUE TITLE
Unsupported ASN.1 value for type SEQUENCE

### ISSUE THREAD

**Issue by vtandroid** [mitshell/libmich#13]
Hi,
 I have this error when i build object from asn.1 file. 
libmich.asn1.utils.ASN1_PROC_NOSUPP: NBAP-ELEMENTARY-PROCEDURE.procedureID: unsu
pported ASN.1 value for type SEQUENCE: { procedureCode id-cellSetup, ddMode fdd }
This is content of my asn.1 file.

```
ProcedureCode   ::= INTEGER (0..255)

ProcedureID     ::= SEQUENCE {
    procedureCode           ProcedureCode,
    ddMode                  ENUMERATED { tdd, fdd, common, ... }
}
NBAP-ELEMENTARY-PROCEDURE ::= CLASS {
    &procedureID    ProcedureID     UNIQUE
}
WITH SYNTAX {
    PROCEDURE ID                        &procedureID
}
cellSetupFDD NBAP-ELEMENTARY-PROCEDURE ::= {
    PROCEDURE ID            { procedureCode id-cellSetup, ddMode fdd } 
}
```

**Comment by mitshell** [comment]
Yes, this is because the parsing of ASN.1 SEQUENCE's value is not
implemented, yet.
If you have time to implement it and submit a patch, it will be very
welcome: see here,
https://github.com/mitshell/libmich/blob/master/libmich/asn1/parsers.py#L1158

2016-03-21 11:50 GMT+01:00 vtandroid <notifications@github.com>:

**Comment by BJamin99** [comment]
I ran into this exact same issue.  Currently working on a patch to get NBAP ASN.1 spec 25.433 Release 9 RAN#62 Version 9.10.0 from 2013-12-19 compiling (not sure if it will compile all X.680 compliant SEQUENCEs).

**Comment by mitshell** [comment]
The patch looks OK, has been merged, so now NBAP should compile.
Thanks.
